name: integrate
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   matrix:
    name: "PHP"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        PHP: ["7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]
        ZTS: ["no"]
        include:
          - PHP: "8.4"
            ZTS: "yes"
    env:
      PHP: ${{ matrix.PHP }}
      GITHUB: "yes"
      enable_debug: "yes"
      enable_maintainer_zts: ${{ matrix.ZTS }}
      enable_session: "yes"
      TEST_PHP_ARGS : "--show-diff"
      REPORT_EXIT_STATUS: "yes"
      NO_INTERACTION: "yes"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.PHP }}
      - name: Install
        run: |
          sudo apt-get install -y re2c
      - name: Prepare
        run: |
            phpize
      - name: Build
        run: |
            ./configure
      - name: Make
        run: |
            make
      - name: Test
        run: |
            make test
