name: integrate
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   matrix:
    name: "PHP"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        PHP: ["7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]
        ZTS: ["no"]
        include:
          - PHP: "8.3"
            ZTS: "yes"
    env:
      PHP: $ {{ matrix.PHP }}
      TEST_PHP_EXECUTABLE: $ {{ matrix.PHP }}
      GITHUB: "yes"
      enable_debug: "yes"
      enable_maintainer_zts: $ {{ matrix.ZTS }}
      enable_session: "yes"
      TEST_PHP_ARGS : "--show-diff"
      REPORT_EXIT_STATUS: "yes"
      NO_INTERACTION: "yes"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install
        run: |
          sudo apt-get install -y \
            php-cli \
            php-pear \
            re2c
      - name: Prepare
        run: |
            phpize
      - name: Build
        run: |
            ./configure
      - name: Make
        run: |
            make
      - name: Test
        run: |
             make test
